---
- name: Deploy Flipkart Clone on Webservers
  hosts: webservers
  become: yes
  tasks:
 
    - name: Install required packages
      yum:
        name:
          - git
          - httpd
        state: present
 
    - name: Ensure httpd is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes
 
    - name: Clone Flipkart Clone repository
      git:
        repo: "https://github.com/Msocial123/Flipkart-Clone.git"
        dest: "/home/ansible/Flipkart-Clone"
        version: main
        force: yes
 
    - name: Copy application code to web root
      copy:
        src: "/home/ansible/Flipkart-Clone/"
        dest: "/var/www/html/"
        owner: apache
        group: apache
        mode: '0755'
        remote_src: yes
 
    - name: Set correct permissions for web root
      file:
        path: /var/www/html
        owner: apache
        group: apache
        recurse: yes